### PR TITLE
Path of the "cbd" binary put in the configuration file

### PR DESCRIPTION
**Pull request by jben94**
I suggest these changes to a need because our installation did not use the default paths of centreon, cbdw did not work.

The problem I see with my changes is to put the `<bin> </ bin>` tags at the top of the XML file for it to work properly.

### CODE REVIEW

**Comment by ganoze** [comment]
Thank you for your PR !

However I do not like the approach of configuring the path to cbd in cbwd's configuration file. I might suit your specific case but is error-prone relative to other users. IMHO there is another way to easily achieve what you want to do without adding another configuration option.

Centreon Broker build system already provides the PREFIX_BIN configuration variable which usually leads to /usr/sbin. It would be easy to add it to vars.hh.in (PREFIX_VAR being already placed there) and then use it in the watchdog to run cbd instead of a hardcoded path. This solution fits nicely within Centreon Broker build system and do not have additional side effects. It also allows you to set where you store your cbd binary when building Centreon Broker.

What do you think about it ?

**Comment by jben94** [comment]
Hi,

Indeed, it would be better with this variable.
I had not thought about this method.

Do you want me to make a new pull request?

**Comment by ganoze** [comment]
No you do not need to do so, I will do it as the correction is quite short. I'm closing this PR though.

Thank you for your feedback.

**Comment by ganoze** [comment]
Fixed in commits 2eac487facc73d71b2e5611e14996b056bf33ba6 (master) and 8d5d52dcd2c86b87cfacd19dbad76fc2ae77359c (3.0).

**Pull request closed without merging**
