### PR TITLE
(fix) MON-4112 fix errors of sql when field has no value

### PR DESCRIPTION
**Pull request by lgcosta**
fix errors of sql when field has no value

### CODE REVIEW

**Comment by lgcosta** [comment]
> Hi @lgcosta, thanks for this pull request.
> I would like to keep it there just because we are migrating the broker mariadb engine and the code on which your patch is applied will no longer exist in a near future. I would prefer to apply this patch to the new branch which is not yet stable. Don't worry the new engine should be available in centreon 19.10.

Great news @bouda1 ! let's not have more QT4? I say this because I have problems porting the Broker to other platforms (eg: FreeBSD)

**Comment by bouda1** [comment]
Hi @lgcosta,

I'm trying to make the same correction as yours in the new sql engine. But I think I'm not agree on your patch. You cannot set the 0 value if the value is not a float number, or we will store wrong values each time no value is returned by a plugin. I'd rather set a null value (with the SQL sense), did you make the test and could you change your patch so we can apply it on master? Or maybe you have a good reason to avoid a such solution.

So, I think I would do the change in this function:
`static inline QVariant check_double(double f) {
  return (std::isnan(f) ? QVariant(QVariant::Double) : QVariant(f));
}`

Something like this should do the work:
`static inline QVariant check_double(double f) {
  return (std::isnan(f) || std::isinf(f) ? QVariant(QVariant::Double) : QVariant(f));
}`

**Comment by lgcosta** [comment]
Hey @bouda1 

You are right, the value must be "NULL" when it does not exist and added the "isinf" in the function just got better. Thanks for tip !

**Comment by lgcosta** [comment]
@bouda1 still I change this PR or will you migrate the code ?

**Comment by lgcosta** [comment]
@bouda1 done. Very thanks !

**Pull request merged**
